# Generated by Django 2.1.7 on 2019-05-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190501_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.BinaryField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssessmentStudent',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Student')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Assessment')),
            ],
            options={
                'db_table': 'assessment_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courselearningobjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'courselearningobjective',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courseoffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grades', models.BinaryField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course')),
            ],
            options={
                'db_table': 'courseoffering',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curriculum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=10, null=True)),
                ('m_date', models.DateField(blank=True, null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'examination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_code', models.ForeignKey(blank=True, db_column='dept_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Department')),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Keylearningoutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
                ('dept_code', models.ForeignKey(blank=True, db_column='dept_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Department')),
            ],
            options={
                'db_table': 'keylearningoutcome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('q_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quiz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'semester',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Curriculum')),
                ('course_code', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course')),
            ],
            options={
                'db_table': 'curriculum_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionCourselearningobjective',
            fields=[
                ('courselearningobjective', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Courselearningobjective')),
                ('value', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_courselearningobjective',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionKeylearningoutcome',
            fields=[
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Question')),
                ('value', models.SmallIntegerField(blank=True, null=True)),
                ('key_learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Keylearningoutcome')),
            ],
            options={
                'db_table': 'question_keylearningoutcome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionInstructor',
            fields=[
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Section')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Instructor')),
            ],
            options={
                'db_table': 'section_instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionStudent',
            fields=[
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Student')),
            ],
            options={
                'db_table': 'section_student',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='courseoffering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Courseoffering'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Assessment'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='dept_code',
            field=models.ForeignKey(blank=True, db_column='dept_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Department'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Semester'),
        ),
        migrations.AddField(
            model_name='courselearningobjective',
            name='course_code',
            field=models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='courseoffering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Courseoffering'),
        ),
        migrations.AddField(
            model_name='questioncourselearningobjective',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentstudent',
            unique_together={('student', 'assessment')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionstudent',
            unique_together={('section', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='sectioninstructor',
            unique_together={('section', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='questionkeylearningoutcome',
            unique_together={('question', 'key_learning_outcome')},
        ),
        migrations.AlterUniqueTogether(
            name='questioncourselearningobjective',
            unique_together={('courselearningobjective', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together={('curriculum', 'course_code')},
        ),
    ]
