# Generated by Django 2.1.7 on 2019-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190501_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
