# Generated by Django 2.1.7 on 2019-05-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.BinaryField(blank=True, null=True)),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'assignment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credit', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courselearningobjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'courselearningobjective',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courseoffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grades', models.BinaryField(blank=True, null=True)),
                ('course_code', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
            options={
                'db_table': 'courseoffering',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'curriculum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=10)),
                ('m_date', models.DateField()),
                ('duration', models.SmallIntegerField()),
                ('type', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'examination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dept_code', models.ForeignKey(db_column='dept_code', on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Keylearningoutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('dept_code', models.ForeignKey(db_column='dept_code', on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
            options={
                'db_table': 'keylearningoutcome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.SmallIntegerField()),
                ('q_date', models.DateField()),
            ],
            options={
                'db_table': 'quiz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'semester',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssessmentStudent',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Student')),
                ('grade', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Curriculum')),
                ('course_code', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
            options={
                'db_table': 'curriculum_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionCourselearningobjective',
            fields=[
                ('courselearningobjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Courselearningobjective')),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'question_courselearningobjective',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionKeylearningoutcome',
            fields=[
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Question')),
                ('value', models.SmallIntegerField()),
                ('key_learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Keylearningoutcome')),
            ],
            options={
                'db_table': 'question_keylearningoutcome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionInstructor',
            fields=[
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Section')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Instructor')),
            ],
            options={
                'db_table': 'section_instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionStudent',
            fields=[
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Section')),
            ],
            options={
                'db_table': 'section_student',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='dep_code',
            field=models.ForeignKey(db_column='dep_code', on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AddField(
            model_name='section',
            name='courseoffering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Courseoffering'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assessment'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='dept_code',
            field=models.ForeignKey(db_column='dept_code', on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Semester'),
        ),
        migrations.AddField(
            model_name='courselearningobjective',
            name='course_code',
            field=models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='courseoffering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Courseoffering'),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='questioncourselearningobjective',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AddField(
            model_name='assessmentstudent',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assessment'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionstudent',
            unique_together={('section', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='sectioninstructor',
            unique_together={('section', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='questionkeylearningoutcome',
            unique_together={('question', 'key_learning_outcome')},
        ),
        migrations.AlterUniqueTogether(
            name='questioncourselearningobjective',
            unique_together={('courselearningobjective', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together={('curriculum', 'course_code')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentstudent',
            unique_together={('student', 'assessment')},
        ),
    ]
